---
booktitle: Proceedings of Thirty Fourth Conference on Learning Theory
shortname: COLT
volume: '134'
year: '2021'
start: 2021-08-15
end: 2021-08-19
published: 2021-07-21
conference_number: '34'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: COLT2021
month: 0
cycles: false
bibtex_editor: Belkin, Mikhail and Kpotufe, Samory
editor:
- given: Mikhail
  family: Belkin
- given: Samory
  family: Kpotufe
title: Proceedings of Machine Learning Research
description: |
  Proceedings of Thirty Fourth Conference on Learning Theory
    Held in Boulder, Colorado, USA on 15-19 August 2021

  Published as Volume 134 by the Proceedings of Machine Learning Research on 21 July 2021.

  Volume Edited by:
    Mikhail Belkin
    Samory Kpotufe

  Series Editors:
    Neil D. Lawrence
    * Mark Reid
date_str: 15--19 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v134"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v134
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v134
email: ''
conference:
  name: Conference on Learning Theory
  url: http://www.learningtheory.org/colt2021/index.html
  location: Boulder, Colorado, USA
  dates:
  - 2021-08-15
  - 2021-08-16
  - 2021-08-17
  - 2021-08-18
  - 2021-08-19
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v134/colt2021.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v134/colt2021.bib
